apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: blog-east2
  namespace: wordpress
spec:
  clusterConditions:
   - type: OK
  clusterSelector:
    matchExpressions: []
    matchLabels:
      name: "east2"
  clusterReplicas: 1
