apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: primary
  namespace: rook-ceph 
spec:
  clusterSelector:
    matchLabels:
      name: "west1"
  clusterReplicas: 1
