apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline
  namespace: wordpress 
subjects:
- kind: ServiceAccount 
  name: pipeline 
  namespace: wordpress
roleRef:
  kind: ClusterRole
  name: pipeline-wordpress
  apiGroup: rbac.authorization.k8s.io
