apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: curl
spec:
  inputs:
    params:
      - name: svc
        description: service to webhook
      - name: port
        description: port to use
        default: 8080
  steps:
    - name: run curl
      image: quay.io/openshift/origin-cli:latest
      command: ["curl"]
      args:
        - "$(inputs.params.svc):$(inputs.params.port)"
