apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: blog-west1 
  namespace: wordpress
spec:
  clusterConditions:
   - type: OK
  clusterSelector:
    matchExpressions: []
    matchLabels:
      name: "west1"
  clusterReplicas: 1
