apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: east2-application-subscription
  namespace: wordpress
  labels:
    name: east2
  annotations:
    apps.open-cluster-management.io/github-path: application/wordpress/overlays/east2
    apps.open-cluster-management.io/github-branch: master
spec:
  channel: wordpress/acm-storage
  placement:
    placementRef:
      kind: PlacementRule
      name: blog-east2
