apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  destination:
    namespace: wordpress
    server: https://kubernetes.default.svc
  project: default
  source:
    path: application/wordpress/overlays/west2
    repoURL: https://github.com/redhat-et/ceph-mirroring.git 
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
