apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: multisite 
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/redhat-et/ceph-mirroring.git
