apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-pipeline
spec:
  resources:
    - name: git-source
      type: git
  params:
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: src
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
  tasks:
  - name: deploy-to-cluster
    taskRef:
      name: deploy-using-kustomize
    params:
      - name: pathToYamlFile
        value:  "$(params.pathToYamlFile)"
    resources:
      inputs:
        - name: git-source
          resource: git-source
