apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: demote-pipeline
spec:
  params:
    - name: svc 
      description: Demote webhook service
      default: site2-demote-rook-ceph.apps.site2.sysdeseng.com 
  tasks:
  - name: curl-to-sync
    taskRef:
      name: curl
    params:
      - name: svc
        value: "$(params.svc)"
