apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: sync-pipeline
spec:
  params:
    - name: svc 
      description: Demote webhook service
      default: site1-resync-rook-ceph.apps.site1.sysdeseng.com
  tasks:
  - name: curl-to-sync
    taskRef:
      name: curl
    params:
      - name: svc
        value: "$(params.svc)"
