apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
   name: storage-sync-management 
   namespace: rook-ceph
spec:
   componentKinds:
      - group: apps.open-cluster-management.io
        kind: Subscription
   descriptor: {}
   selector:
      matchExpressions:
         - key: name 
           operator: In
           values:
              - west1
              - west2
