resources:
- mysql-deployment.yaml
- wordpress-route.yaml
- namespace.yaml
- mysql-service.yaml
- wordpress-deployment.yaml
- wordpress-service.yaml
- mysql-secret.yaml
- wp-config-secret.yaml
- mysql-pvc.yaml
- wordpress-pvc.yaml
