apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  namespace: wordpress
  labels:
    app: wordpress
spec:
  storageClassName: rook-ceph-block-mirror-et2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
