apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: storage-management
  namespace: rook-ceph 
spec:
  type: GitHub
  pathname: https://github.com/redhat-et/ceph-mirroring.git
