apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: storage-clusters 
  namespace: rook-ceph
spec:
  clusterConditions:
   - type: OK
  clusterSelector:
    matchExpressions: []
    matchLabels:
      cloud: "Amazon"
  clusterReplicas: 2
