apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: site-switch
  namespace: argocd
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: default
  source:
    path: rbd-jobs/both
    repoURL: https://github.com/redhat-et/ceph-mirroring.git 
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
