apiVersion: batch/v1
kind: Job
metadata:
  name: demote-job-6
  namespace: rook-ceph
  labels:
    app: ceph-toolbox-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      initContainers:
      - name: config-init-demote
        image: quay.io/rcook/storage-rehost:toolbox
        command: ["/tini"]
        args: ["-g", "-s", "--", "/usr/local/bin/toolbox.sh", "--skip-watch"]
        imagePullPolicy: IfNotPresent
        env:
        - name: ROOK_ADMIN_SECRET
          valueFrom:
            secretKeyRef:
              name: rook-ceph-mon
              key: admin-secret
        volumeMounts:
        - mountPath: /etc/ceph
          name: ceph-config
        - name: mon-endpoint-volume
          mountPath: /etc/rook
      containers:
      - name: script-demote
        image: quay.io/rcook/storage-rehost:toolbox
        volumeMounts:
        - mountPath: /etc/ceph
          name: ceph-config
          readOnly: true
        command:
        - "bash"
        - "-c"
        - |
          rbd mirror image demote scottpool4/mysql-pv-claim-wordpresse3330f81-bb9b-11ea-bd87-0a580a83002e
          rbd mirror image demote scottpool4/wp-pv-claim-wordpresse335727c-bb9b-11ea-bd87-0a580a83002e
      volumes:
      - name: mon-endpoint-volume
        configMap:
          name: rook-ceph-mon-endpoints
          items:
          - key: data
            path: mon-endpoints
      - name: ceph-config
        emptyDir: {}
      restartPolicy: Never
