apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: primary
  namespace: rook-ceph
  labels:
    name: east1
  annotations:
    apps.open-cluster-management.io/github-path: rbd-jobs/both
    apps.open-cluster-management.io/github-branch: master
spec:
  channel: rook-ceph/wordpress 
  placement:
    placementRef:
      kind: PlacementRule
      name: primary
