apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: rbd-mirror-action
spec:
  inputs:
    params:
      - name: pool
        type: string
        description: name of pool
      - name: toolbox
        type: string
        description: name of toolbox pod
      - name: action
        type: string
        description: action to run resync|demote|promote
      - name: image1
        type: string
        description: name of image 1
      - name: image2
        type: string
        description: name of image 2
      - name: SCRIPT
        description: The OpenShift CLI arguments to run
        type: string
        default: "oc $@"
  steps:
    - name: exec-toolbox-action-image-1
      image: quay.io/openshift/origin-cli:latest
      script: "$(inputs.params.SCRIPT)"
      args:
        - "exec"
        - "-ti"
        - $(inputs.params.toolbox)
        - "-n"
        - "rook-ceph"
        - "rbd mirror image $(inputs.params.action) $(inputs.params.pool)/$(inputs.params.image1)"
    - name: exec-toolbox-action-image-2
      image: quay.io/openshift/origin-cli:latest
      script: "$(inputs.params.SCRIPT)"
      args:
        - "exec"
        - "-ti"
        - $(inputs.params.toolbox)
        - "-n"
        - "rook-ceph"
        - "rbd mirror image $(inputs.params.action) $(inputs.params.pool)/$(inputs.params.image2)"
